services:
  - type: web
    name: rlshield
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn --chdir RL RL.wsgi:application
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.13.0
